version: '3.8'

services:
  backend:
    build: ./back
    container_name: fastapi-app
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - READ_DATABASE_URL=${READ_DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: vue-app
    restart: always
    ports:
      - "8080:80"  # 호스트의 8080 포트로 노출 (충돌 회피)
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge